services:
  - type: web
    name: rate-myshow
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn rate_myshow.wsgi"
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: OMDB_API_KEY
        value: "d5b0159b"
