# Generated by Django 5.2.14 on 2026-05-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=20)),
                ('poster', models.URLField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, to='titles.actor')),
                ('genres', models.ManyToManyField(blank=True, to='titles.genre')),
            ],
        ),
    ]
